(function registerReasonCodes(globalScope) {
  const reasonCodes = Object.freeze({
    MISSING_ACCESSIBLE_NAME: "MISSING_ACCESSIBLE_NAME",
    EXISTING_ACCESSIBLE_NAME_PRESERVED: "EXISTING_ACCESSIBLE_NAME_PRESERVED",
    NON_SEMANTIC_CLICKABLE_CONTROL: "NON_SEMANTIC_CLICKABLE_CONTROL",
    KEYBOARD_ACCESS_MISSING: "KEYBOARD_ACCESS_MISSING",
    FORM_LABEL_MISSING: "FORM_LABEL_MISSING",
    IMAGE_ALT_MISSING: "IMAGE_ALT_MISSING",
    LANDMARK_MISSING: "LANDMARK_MISSING",
    ADAPTATION_ROLLED_BACK: "ADAPTATION_ROLLED_BACK"
  });

  globalScope.BAA_REASON_CODES = reasonCodes;
})(globalThis);
