import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { spawnSync } from "node:child_process";
import test from "node:test";
const chromePath = process.env.BAA_CHROME_PATH || "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

async function browserChecks() {
  const check = (value, message) => { if (!value) throw new Error(message); };
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  async function until(condition) { for (let i = 0; i < 50; i++) { if (condition()) return; await wait(20); } throw new Error("Timed out"); }
  const reporter = document.createElement("pre"); reporter.id = "test-result"; reporter.dataset.baaOwned = "true";
  const mount = html => { document.body.innerHTML = html; document.title = "Summary fixture"; document.body.append(reporter); };
  const collect = options => BAA_PAGE_CONTEXT.collect(document, options);
  const content = context => JSON.stringify(context.regions);
  const article = '<header><nav><a href="#outside">Home</a></nav></header><main><h1>School report</h1><article><h2>Community meeting</h2><p id="focus" tabindex="0">Residents discussed better <span>lighting</span> and <a id="inline" href="#focus">safer crossings</a> after school. The proposal will be reviewed next week.</p><p>Teachers described safe routes and asked for clearer signs near the school entrance.</p><p>The final schedule will be published after consultation with local families.</p></article><aside aria-label="Related articles"><article><h3>RelatedStoryMarker</h3><p>Unrelated article content</p><a href="#related">Read related story</a></article><a href="#another">Another recommendation</a></aside><div role="alert">Security warning: verify the sender before opening attachments.</div></main><footer><a href="#privacy">Privacy</a></footer>';
  let assistant;
  try {
    mount(article);
    const focused = document.getElementById("focus"); focused.focus();
    let snapshot = collect({ scope: "page" }), plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.primaryIds.length === 1, "Article main region is ambiguous");
    const main = snapshot.context.regions.find(region => region.id === plan.primaryIds[0]);
    check(main.type === "article" && !JSON.stringify(main).includes("RelatedStoryMarker"), "Related stories contaminated article summary");
    check(main.blocks.some(block => block.text.includes("better lighting and safer crossings after school")), "Inline paragraph text was omitted");
    check(plan.notices.some(value => value.includes("Security warning")), "Important notice omitted");
    const region = collect({ scope: "region", focusedElement: document.getElementById("inline") });
    check(region.context.regions.find(item => item.id === region.context.selectedRegionId).type === "article", "Focused link did not resolve enclosing article");
    const requests = [], held = [], cancellations = [];
    let fail = false, hold = false;
    assistant = BAA_SUMMARY_ASSISTANT.createSummaryAssistant({ documentRef: document, announcer: { announce() {} }, sendMessage: async message => {
      if (message.type === "BAA_CANCEL_SUMMARY") { cancellations.push(message.requestId); return {}; }
      requests.push(message);
      if (fail) throw new Error("Offline");
      const response = { summary_bn: "বাসিন্দারা নিরাপদ চলাচল ও উন্নত আলোর ব্যবস্থা নিয়ে আলোচনা করেছেন।", sections: message.context.regions.filter(region => region.blocks.length).map(region => ({ region_id: region.id, summary_bn: "সভায় নিরাপত্তা নিয়ে আলোচনা হয়েছে।", source_ids: region.blocks.map(block => block.id) })) };
      if (hold) return new Promise(resolve => held.push(() => resolve(response)));
      await wait(20); return response;
    } });
    assistant.start();
    const host = [...document.querySelectorAll("[data-baa-owned]")].find(element => element.shadowRoot);
    const shadow = host.shadowRoot, dialog = shadow.querySelector("dialog");
    const press = code => { const event = new KeyboardEvent("keydown", { code, altKey: true, shiftKey: true, bubbles: true, cancelable: true }); document.dispatchEvent(event); check(event.defaultPrevented, "Shortcut not handled: " + code); };
    press("KeyA"); await until(() => requests.length === 1 && shadow.getElementById("status").textContent.includes("প্রস্তুত"));
    check(dialog.open && requests[0].context.scope === "page", "Alt Shift A failed");
    check(requests[0].context.regions.every(region => region.type === "article"), "Secondary content sent as main");
    check(shadow.getElementById("results").textContent.includes("বাসিন্দারা"), "AI summary not rendered");
    check(shadow.activeElement === shadow.querySelector("[data-summary-ai] p") && !shadow.getElementById("results").hasAttribute("aria-busy"), "Completed page summary did not focus its readable content");
    check(!shadow.getElementById("detail"), "Summary preference still appears in dialog");
    assistant.setDetail("brief"); shadow.getElementById("refresh").click();
    await until(() => requests.length === 2 && shadow.getElementById("status").textContent.includes("প্রস্তুত"));
    check(requests[1].context.detail === "brief", "Saved detail not applied");
    check(shadow.activeElement === shadow.querySelector("[data-summary-ai] p"), "Regenerated summary did not focus its content");
    check(shadow.getElementById("results").firstElementChild.hasAttribute("data-summary-ai"), "Content gist does not lead the results");
    check(shadow.getElementById("results").querySelectorAll("li").length <= 5 && !shadow.getElementById("results").textContent.includes("সনাক্ত করা অঞ্চল"), "Summary contains a control inventory");
    shadow.getElementById("close").click();
    check(document.activeElement === focused && !dialog.open, "Closing panel did not restore focus");
    document.getElementById("inline").focus(); press("KeyS");
    await until(() => requests.length === 3 && shadow.getElementById("status").textContent.includes("প্রস্তুত"));
    check(requests[2].context.scope === "region", "Alt Shift S failed");
    check(shadow.activeElement === shadow.querySelector("[data-summary-ai] p"), "Completed region summary did not focus its content");
    dialog.dispatchEvent(new Event("cancel", { cancelable: true }));
    check(!dialog.open && document.activeElement === document.getElementById("inline"), "Escape did not restore link focus");
    fail = true; press("KeyA"); await until(() => shadow.getElementById("status").textContent.includes("পাওয়া যাচ্ছে না"));
    check(shadow.getElementById("results").textContent.includes("পৃষ্ঠার পরিচয়"), "Local overview unavailable on failure");
    check(shadow.activeElement === shadow.getElementById("refresh"), "Failed summary did not focus retry button");
    fail = false; shadow.getElementById("refresh").click();
    await until(() => shadow.getElementById("status").textContent.includes("প্রস্তুত"));
    check(shadow.activeElement === shadow.querySelector("[data-summary-ai] p"), "Successful retry did not focus summary content");
    fail = true; shadow.getElementById("refresh").click();
    await until(() => shadow.getElementById("status").textContent.includes("পাওয়া যাচ্ছে না"));
    check(shadow.activeElement === shadow.getElementById("refresh"), "Failed regeneration did not focus retry button");
    shadow.getElementById("close").click(); fail = false; hold = true;
    press("KeyA"); await until(() => held.length === 1);
    const before = cancellations.length;
    document.querySelector("nav a").textContent = "Changed menu label";
    document.querySelector("nav").setAttribute("aria-expanded", "true");
    await wait(250);
    check(cancellations.length === before, "Unrelated navigation cancelled main-content summary");
    const authored = focused.firstChild.nodeValue;
    focused.firstChild.__baaOriginalText = authored;
    focused.firstChild.__baaAppliedText = "অনুবাদ করা মূল লেখা।";
    focused.firstChild.__baaTranslated = true;
    focused.firstChild.nodeValue = focused.firstChild.__baaAppliedText;
    await wait(250);
    check(cancellations.length === before, "Extension translation cancelled main-content summary");
    focused.firstChild.nodeValue = "Publisher changed this article.";
    await wait(250); held.shift()(); await wait(40);
    check(cancellations.length > 0 && !shadow.getElementById("results").textContent.includes("বাসিন্দারা"), "Stale summary applied");
    check(shadow.activeElement === shadow.getElementById("refresh"), "Content change during generation did not focus retry button");
    shadow.getElementById("close").click(); hold = false; press("KeyA");
    await until(() => shadow.getElementById("status").textContent.includes("প্রস্তুত"));
    focused.firstChild.nodeValue = "The publisher changed the completed report.";
    await until(() => shadow.getElementById("status").textContent.includes("মূল তথ্য বদলেছে"));
    check(shadow.activeElement === shadow.getElementById("refresh") && !shadow.querySelector("[data-summary-ai]"), "Completed summary invalidation did not focus retry button and remove stale content");
    shadow.getElementById("close").click(); hold = true; press("KeyA"); await until(() => held.length === 1);
    focused.firstChild.nodeValue = "The publisher changed the report just before the response.";
    held.shift()();
    await until(() => shadow.getElementById("status").textContent.includes("মূল তথ্য বদলেছে"));
    check(shadow.activeElement === shadow.getElementById("refresh") && !shadow.querySelector("[data-summary-ai]"), "Response-time invalidation did not focus retry button");
    shadow.getElementById("close").click(); press("KeyA"); await until(() => held.length === 1);
    window.dispatchEvent(new Event("pagehide"));
    check(!dialog.open, "Navigation did not close/cancel summary panel");
    assistant.stop(); held.shift()(); await wait(20);
    check(!host.isConnected, "Panel survived disablement"); assistant = null;

    mount('<main aria-label="Search results"><h1>Search results</h1><ol><li><a href="/one">First result</a><p>Description of first result.</p></li><li><a href="/two">Second result</a><p>Description of second result.</p></li></ol><button>Next page</button></main>');
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.purpose === "results" && plan.canGenerate, "Search results treated as secondary");
    check(content(snapshot.context).includes("Description of second"), "Search description omitted");
    mount('<main><h1>Application</h1><form><h2>Application details</h2><p>Applications close on Friday.</p><label for="person">Name</label><input id="person" required minlength="8" aria-invalid="true"><button>Submit application</button><div role="alert">Provide the required document.</div></form></main>');
    Object.defineProperty(document.getElementById("person"), "value", { get() { throw new Error("Field value was read"); } });
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    const form = snapshot.context.regions.find(region => region.type === "form");
    check(plan.purpose === "form" && form.controls.some(control => control.required && control.invalid && control.constraints.minlength === "8"), "Form requirements omitted");
    check(plan.notices.some(value => value.includes("required document")), "Form error omitted");
    mount('<main aria-label="Product"><h1>Product: school bag</h1><p>Price: 500 BDT</p><p>Available next week.</p><button>Buy now</button></main>');
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.purpose === "product" && plan.canGenerate && content(snapshot.context).includes("500 BDT"), "Product price/purpose omitted");
    mount('<main><h1>Dashboard</h1><table><caption>Attendance</caption><thead><tr><th>Class</th><th>Present</th></tr></thead><tbody><tr><td>A</td><td>20</td></tr></tbody></table><section><h2>Announcements</h2><p>School closes early today.</p></section></main>');
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.purpose === "dashboard" && snapshot.context.regions.some(region => region.type === "table" && region.blocks.some(block => block.text.includes("Present: 20"))), "Table header/value relationship lost");
    mount('<main><h1>Bank account</h1><p>Balance: 500 BDT. Contact person@example.com.</p><form><label for="password">Password</label><input type="password" id="password"><button>Continue</button></form></main>');
    Object.defineProperty(document.getElementById("password"), "value", { get() { throw new Error("Password value was read"); } });
    snapshot = collect();
    check(snapshot.context.privateContext && snapshot.context.regions.every(region => region.blocks.length === 0), "Private text exposed by default");
    check(!JSON.stringify(snapshot.context).includes("500") && !JSON.stringify(snapshot.context).includes("example.com"), "Private text survived structural mode");
    const privateRequests = [];
    assistant = BAA_SUMMARY_ASSISTANT.createSummaryAssistant({ documentRef: document, announcer: { announce() {} }, sendMessage: async message => {
      if (message.type === "BAA_CANCEL_SUMMARY") return {};
      privateRequests.push(message); return { summary_bn: "অ্যাকাউন্টের তথ্যের সারাংশ।", sections: [] };
    } });
    assistant.start(); await assistant.invoke("page");
    check(privateRequests.length === 0, "Private page triggered provider call");
    const privateShadow = [...document.querySelectorAll("[data-baa-owned]")].find(element => element.shadowRoot).shadowRoot;
    check(!privateShadow.getElementById("privacy").hidden, "Private content choice unavailable");
    privateShadow.getElementById("allowPrivate").checked = true;
    privateShadow.getElementById("regions").value = snapshot.context.regions.find(region => snapshot.targets.get(region.id).tagName === "MAIN").id;
    privateShadow.getElementById("summarizeRegion").click();
    await until(() => privateRequests.length === 1);
    check(privateRequests[0].context.allowPrivateContent && !JSON.stringify(privateRequests[0]).includes("example.com"), "Private request not minimized");
    check(!privateShadow.getElementById("allowPrivate").checked, "Private permission persisted"); assistant.stop(); assistant = null;
    mount('<main><section><h2>Lessons</h2><p>Study material is available for the next class.</p></section><section><h2>Assignments</h2><p>Submit homework before the end of the week.</p></section></main>');
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.canGenerate && plan.primaryIds.length === 3, "Nested main sections incorrectly treated as competing regions");
    mount('<section><h2>Lessons</h2><p>Study material is available for the next class.</p></section><section><h2>Assignments</h2><p>Submit homework before the end of the week.</p></section>');
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.primaryIds.length === 0 && !plan.canGenerate, "Independent ambiguous regions merged automatically");
    snapshot = collect({ scope: "region", focusedElement: document.querySelector("section p") });
    check(BAA_SUMMARY_PLANNER.plan(snapshot.context).canGenerate, "Region choice unavailable");

    mount('<nav aria-label="Contents"><a href="#history">History</a><a href="#types">Types</a></nav><main><h1>Screen reader</h1><form role="search"><input type="search" aria-label="Search this site"><button>Search</button></form><div id="prose"><p tabindex="0" id="prose-focus">A screen reader renders text and image content as speech or braille.</p><section><h2 id="history">History</h2><p>Early screen readers helped people use computers.</p></section><section><h2 id="types">Types</h2><p>Modern readers use accessibility APIs and support customization.</p></section><table><tr><td>Speech output</td><td>Available</td></tr></table><section><h2>References</h2><ol><li>ReferenceMarker <a href="/reference">Reference link</a></li></ol></section><table role="presentation"><tr><td><a href="/unrelated">NavigationMarker</a> <a href="/another">Another topic</a> <a href="/last">Other topics</a></td></tr></table><section aria-label="Editorial notes"><p>MaintenanceMarker: improve this documentation.</p><a href="/editing">Improve documentation</a></section><section><h2>See also</h2><ul><li><a href="/list">List of screen readers</a></li><li><a href="/magnifier">Screen magnifier</a></li></ul></section></div><aside aria-label="Appearance"><input type="radio" aria-label="Small"><input type="radio" aria-label="Large"></aside></main>');
    const prose = document.getElementById("prose-focus");
    document.getElementById("history").innerHTML += ' <span>[<a href="/edit">edit</a>]</span>';
    document.querySelector("#prose section:last-child h2").innerHTML += ' <span>[<a href="/edit-related" title="Edit section: See also">edit</a>]</span>';
    prose.innerHTML += Array.from({ length: 100 }, (_, i) => ' <a href="/inline-' + i + '">InlineTopic' + i + '</a><sup><a href="#citation-' + i + '">[' + i + ']</a></sup>').join("");
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(plan.purpose === "article" && plan.canGenerate, "Unmarked prose classified as dashboard or search form");
    const selectedProse = snapshot.context.regions.filter(region => plan.primaryIds.includes(region.id));
    check(selectedProse.some(region => region.blocks.some(block => block.text.includes("Early screen readers"))) && selectedProse.some(region => region.blocks.some(block => block.text.includes("Modern readers"))), "Nested unmarked prose omitted");
    check(snapshot.targets.get(plan.primaryIds[0]) === document.getElementById("prose"), "Inference did not find the narrow prose container");
    check(!JSON.stringify(selectedProse).includes("ReferenceMarker") && !JSON.stringify(selectedProse).includes("NavigationMarker") && !JSON.stringify(selectedProse).includes("MaintenanceMarker"), "Secondary sections contaminated gist");
    check(!JSON.stringify(selectedProse).includes("[edit]"), "Inline editorial utility contaminated prose");
    check(plan.importantControls.length === 2 && plan.importantControls.every(control => !control.name.includes("InlineTopic")), "Inline citations crowded out useful links");
    const originalSelection = JSON.stringify(selectedProse);
    for (const [index, element] of [...document.querySelectorAll("main *")].entries()) element.className = 'arbitrary-layout-' + index % 7;
    const renamed = collect(); const renamedPlan = BAA_SUMMARY_PLANNER.plan(renamed.context);
    check(JSON.stringify(renamed.context.regions.filter(region => renamedPlan.primaryIds.includes(region.id))) === originalSelection, "Summary selection depends on site CSS classes");
    const focusedProse = collect({ scope: "region", focusedElement: prose });
    check(focusedProse.targets.get(focusedProse.context.selectedRegionId) === document.getElementById("prose"), "Focused unmarked prose did not resolve its inferred article");
    prose.focus();
    const proseRequests = [];
    assistant = BAA_SUMMARY_ASSISTANT.createSummaryAssistant({ documentRef: document, announcer: { announce() {} }, sendMessage: async message => {
      if (message.type === "BAA_CANCEL_SUMMARY") return {};
      proseRequests.push(message); return { summary_bn: "স্ক্রিন রিডার লেখা ও ছবির তথ্য কণ্ঠস্বর বা ব্রেইলে প্রকাশ করে।", sections: [] };
    } });
    assistant.start(); await assistant.invoke("page");
    const proseShadow = [...document.querySelectorAll("[data-baa-owned]")].find(element => element.shadowRoot).shadowRoot;
    check(proseRequests.length === 1 && proseRequests[0].context.purpose === "article", "Unmarked prose never requested a content summary");
    check(proseShadow.getElementById("results").querySelectorAll("li").length === 2 && proseShadow.getElementById("results").querySelectorAll("a[href]").length === 2, "Useful links not bounded/clickable");
    check(proseShadow.getElementById("regionChoice").hidden, "Unmarked article unnecessarily asks for region selection");
    assistant.stop(); assistant = null;
    mount('<main><h1>Directory</h1><table><caption>Service directory</caption><thead><tr><th>Service</th><th>Contact</th></tr></thead><tbody><tr><td><a href="/a">Alpha service</a></td><td><a href="/a-help">Alpha contact</a></td></tr><tr><td><a href="/b">Beta service</a></td><td><a href="/b-help">Beta contact</a></td></tr></tbody></table></main>');
    snapshot = collect(); plan = BAA_SUMMARY_PLANNER.plan(snapshot.context);
    check(snapshot.context.regions.some(region => region.type === "table" && !region.secondary && region.blocks.length > 0) && plan.canGenerate, "Link-rich data table misclassified as navigation");
    mount('<main>Plain report text without paragraph markup.<p>Following paragraph.</p><output aria-live="polite">Submission completed.</output></main>');
    snapshot = collect();
    check(snapshot.context.regions.some(region => region.blocks[0]?.text.includes("Plain report text")), "Plain region text omitted or reordered");
    check(BAA_SUMMARY_PLANNER.plan(snapshot.context).notices.some(value => value.includes("Submission completed")), "Completion status omitted");
    mount('<main><h1>Documentation</h1><p id="long"></p><p hidden>HiddenSecret</p><div contenteditable="true">EditableSecret</div><iframe title="Embedded chart"></iframe></main>');
    document.getElementById("long").textContent = "Long report sentence with useful details. ".repeat(3500) + "EndOfLongReport";
    snapshot = collect();
    check(!content(snapshot.context).includes("HiddenSecret") && !content(snapshot.context).includes("EditableSecret"), "Hidden/editable content leaked");
    check(snapshot.context.coverage.limitations.includes("content_limited") && snapshot.context.coverage.limitations.includes("embedded_content_limited"), "Coverage limit silent");
    check(snapshot.context.regions.every(region => region.blocks.every(block => block.text.length <= 1200)), "Chunk exceeds schema bound");
    const later = document.createElement("section"); later.innerHTML = '<h2>Later section</h2><p tabindex="0">A focused region after the large report.</p>'; document.querySelector("main").append(later);
    snapshot = collect({ scope: "region", focusedElement: later.querySelector("p") });
    check(BAA_SUMMARY_PLANNER.plan(snapshot.context).canGenerate && !snapshot.context.coverage.limitations.includes("content_limited"), "Earlier large content exhausted focused-region budget");
    reporter.textContent = btoa(JSON.stringify({ ok: true, cases: 9 }));
  } catch (error) { assistant?.stop(); reporter.textContent = btoa(JSON.stringify({ ok: false, error: error.message, stack: error.stack })); }
}

test("Chrome summary integration across page types, shortcuts, privacy, focus and cancellation", { skip: !existsSync(chromePath) }, async () => {
  const directory = await mkdtemp(join(tmpdir(), "baa-summary-test-"));
  try {
    const scripts = await Promise.all(["accessibilityCore", "pageContextCollector", "pageSummaryPlanner", "summaryAssistant"].map(file => readFile(new URL("../src/content/" + file + ".js", import.meta.url), "utf8")));
    const page = join(directory, "summary.html");
    await writeFile(page, '<!doctype html><html><meta charset="utf-8"><base href="https://summary.test/"><body>' + scripts.map(source => "<script>" + source + "</script>").join("\n") + "<script>(" + browserChecks.toString() + ")();</script></body></html>");
    const browser = spawnSync(chromePath, ["--headless", "--disable-gpu", "--no-first-run", "--no-default-browser-check", "--disable-background-networking", "--user-data-dir=" + join(directory, "profile"), "--virtual-time-budget=15000", "--dump-dom", pathToFileURL(page).href], { encoding: "utf8", timeout: 45000, maxBuffer: 2_000_000, windowsHide: true });
    assert.ifError(browser.error); assert.equal(browser.status, 0, browser.stderr.slice(-1200));
    const encoded = browser.stdout.match(/<pre id="test-result"[^>]*>([A-Za-z0-9+/=]+)<\/pre>/)?.[1];
    assert.ok(encoded, "Chrome did not finish checks: " + browser.stderr.slice(-1200));
    const report = JSON.parse(Buffer.from(encoded, "base64").toString("utf8"));
    assert.equal(report.ok, true, JSON.stringify(report));
  } finally { await rm(directory, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }); }
});
